/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.JOptionPane;

/**
 *
 * @author edg02
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_salir = new javax.swing.JMenuItem();
        menu_figuras = new javax.swing.JMenu();
        menu_numeros = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_palabras = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();
        menu_manual = new javax.swing.JMenuItem();
        menu_acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Áreas NEXBIN-220");
        setAlwaysOnTop(true);

        escritorio.setToolTipText("");
        escritorio.setFocusable(false);
        escritorio.setNextFocusableComponent(escritorio);

        jLabel1.setText("Elige las opciones de Juego en Actividades");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Bienvenidos");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jMenuBar1.setToolTipText("");

        menu_archivo.setText("Archivo");
        menu_archivo.add(jSeparator1);

        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_salir);

        jMenuBar1.add(menu_archivo);

        menu_figuras.setText("Actividades");

        menu_numeros.setText("Juguemos con los números");
        menu_numeros.setToolTipText("");
        menu_numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_numerosActionPerformed(evt);
            }
        });
        menu_figuras.add(menu_numeros);
        menu_figuras.add(jSeparator2);

        menu_palabras.setText("Juguemos con las palabras");
        menu_palabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_palabrasActionPerformed(evt);
            }
        });
        menu_figuras.add(menu_palabras);

        jMenuBar1.add(menu_figuras);

        menu_ayuda.setText("Ayuda");

        menu_manual.setText("Manual");
        menu_ayuda.add(menu_manual);

        menu_acerca.setText("Acerca de");
        menu_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_acercaActionPerformed(evt);
            }
        });
        menu_ayuda.add(menu_acerca);

        jMenuBar1.add(menu_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        int n = JOptionPane.showConfirmDialog(null , "¿DESEA CERRAR EL PROGRAMA?",
        "Confirmación", JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.YES_OPTION)
             {
                JOptionPane.showMessageDialog(null, "GRACIAS POR UTILIZAR EL PROGRAMA");
                    System.exit(0);
             } 
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_palabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_palabrasActionPerformed
        Words t = new Words();
        escritorio.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_menu_palabrasActionPerformed

    private void menu_numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_numerosActionPerformed
        Numbers t = new Numbers();
        escritorio.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_menu_numerosActionPerformed

    private void menu_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_acercaActionPerformed
        // Texto para créditos
        JOptionPane.showMessageDialog(null, "<html>El Juego de la Selva (2021).<br>Yosthyn Gutierrez.<br>Edgardo Rivera. <br>Maylyn Oviedo. <br>CI, Ceduc Cqbo 2021.</html>");
    }//GEN-LAST:event_menu_acercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menu_acerca;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_ayuda;
    private javax.swing.JMenu menu_figuras;
    private javax.swing.JMenuItem menu_manual;
    private javax.swing.JMenuItem menu_numeros;
    private javax.swing.JMenuItem menu_palabras;
    private javax.swing.JMenuItem menu_salir;
    // End of variables declaration//GEN-END:variables
}

